---
title: "GitHub"
subtitle: "Introduction to Data Science (BIOL7800)\nhttps://introdatasci.dlilab.com/"
author: "Daijiang Li"
institute: "LSU"
date: "2023/09/05"
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: "https://platform.twitter.com/widgets.js"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.align='center', out.width = '95%')
```

class: middle

# We will continue to use [this excellent workshop material](https://carpentries-incubator.github.io/git-novice-branch-pr/) developed by Software Carpentry for today's lecture.

---

# Connect local git repository with GitHub

1. Go to <https://github.com>, login, and create a repository named as 'planets', without adding README, .gitignore, and license
2. Copy the code from the "... pushing an existing repository to Github through command line"
3. Paste and run the code in the terminal; since you have not connected with GitHub yet, you may get an error about pushing your materials to GitHub.
4. Download GitHub Command line tool at <https://cli.github.com>, [install it](https://github.com/cli/cli#installation). If you use Mac, install Homebrew and just type `brew install gh` in the terminal
5. Once installed GitHub Cli, in terminal, type `gh auth login`
6. Following the instruction in terminal and authorize GitHub through web browser
7. You may need to close and reopen RStudio to see the color Pull/Push buttons (if you use RStudio)
8. Then commit and push the materials to GitHub and we are good to go

**Note: If you have already connected with GitHub from your computer previously, you can skip steps 4-6.**

<!-- # Token -->

<!-- [Token required](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) since August 12. 2021. -->

<!-- 1. [Create personal access token on Github](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) -->
<!-- 2. [Caching your GitHub credentials in Git](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) -->
<!--     + Let's choose the [Github CLI](https://github.com/cli/cli#installation) option -->

